name: aerasync
description: A Flutter app for comparing aerators in shrimp farming with a step-by-step survey and ranked results.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  http: ^1.2.2
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  flutter_svg: ^2.1.0
  fl_chart: ^0.65.0 # Added for data visualization
  pdf: ^3.11.3
  flutter_pdfview: ^1.4.0+1
  path_provider: ^2.1.5
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.6
  build_runner: ^2.3.3 # Downgraded to a version compatible with Dart SDK 3.2.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: NotoSerif
      fonts:
        - asset: web/fonts/NotoSerif-Black.ttf
        - asset: web/fonts/NotoSerif-Bold.ttf
          weight: 700
        - asset: web/fonts/NotoSerif-BlackItalic.ttf
        - asset: web/fonts/NotoSerif-BoldItalic.ttf
          weight: 700
          style: italic

    - family: NotoSans
      fonts:
        - asset: web/fonts/NotoSans-Black.ttf
        - asset: web/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: web/fonts/NotoSans-BlackItalic.ttf
        - asset: web/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Roboto
      fonts:
        - asset: web/fonts/Roboto-Black.ttf
        - asset: web/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: web/fonts/Roboto-BlackItalic.ttf
          style: italic

    - family: DejaVuSans
      fonts:
        - asset: web/fonts/DejaVuSans.ttf
        - asset: web/fonts/DejaVuSans-Bold.ttf
          weight: 700

    - family: ArialUnicodeMS
      fonts:
        - asset: web/fonts/ArialUnicodeMS.otf
        - asset: web/fonts/ArialUnicodeMS-Bold.otf
          weight: 700
  assets:
    - web/assets/
    - web/icons/aerasync64.webp
    - web/icons/aerasync180.webp
    - web/icons/aerasync.webp
    - web/icons/background.webp
    - web/assets/wave.svg
    - web/fonts/NotoSerif-Black.ttf
    - web/fonts/NotoSerif-Bold.ttf
    - web/fonts/NotoSerif-BlackItalic.ttf
    - web/fonts/NotoSerif-BoldItalic.ttf
    - web/fonts/NotoSans-Black.ttf
    - web/fonts/NotoSans-Bold.ttf
    - web/fonts/NotoSans-BlackItalic.ttf
    - web/fonts/NotoSans-BoldItalic.ttf
    - web/fonts/Roboto-Black.ttf
    - web/fonts/Roboto-Bold.ttf
    - web/fonts/Roboto-BlackItalic.ttf
    - web/fonts/DejaVuSans.ttf
    - web/fonts/DejaVuSans-Bold.ttf
    - web/fonts/ArialUnicodeMS.otf
    - web/fonts/ArialUnicodeMS-Bold.otf
