name: aerasync
description: A Flutter app for comparing aerators in shrimp farming with a step-by-step survey and ranked results.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  http: ^1.2.2
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.6
  build_runner: ^2.3.3 # Downgraded to a version compatible with Dart SDK 3.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - web/icons/aerasync64.webp
    - web/icons/aerasync180.webp
    - web/icons/aerasync.webp
    - web/manifest.json
