name: AeraSync
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  url_launcher: ^6.0.0
  universal_html: ^2.2.4
  fl_chart: ^0.70.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  shared_preferences: ^2.5.3
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  async: ^2.13.0
  material_color_utilities: ^0.12.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  vm_service: ^15.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/aerasync.png
    - assets/data/o2_temp_sal_100_sat.json
    - assets/data/shrimp_respiration_salinity_temperature_weight.json