name: aerasync
description: A Flutter app for aerator comparison in aquaculture.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  fl_chart: ^0.68.0
  pdf: ^3.10.0
  printing: ^5.12.0

  
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.3.0
  html: ^0.15.4
  universal_html: ^2.2.4
  dio: ^5.0.0
  shared_preferences: ^2.3.0
  logging: ^1.3.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  build_runner: ^2.1.0
  build_web_compilers: ^4.1.4
  mockito: ^5.0.0
  analyzer: ^5.13.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
  assets:
    - assets/data/o2_temp_sal_100_sat.json
    - assets/data/shrimp_respiration_salinity_temperature_weight.json
    - web/assets/wave.svg
    - web/icons/aerasync64.webp
    - web/icons/aerasync64.png
    - web/icons/aerasync180.webp
    - web/icons/aerasync180.png
    - web/icons/aerasync512.webp
    - web/icons/aerasync512.png
    - web/icons/aerasync1024.webp
    - web/icons/aerasync1024.png
    - web/icons/aerasync.webp
    - web/manifest.json