name: AeraSync
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  fl_chart: ^0.68.0
  universal_html: ^2.2.4
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  url_launcher: ^6.3.0
  pdf: ^3.10.8
  printing: ^5.12.0
  http: ^1.2.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/data/o2_temp_sal_100_sat.json
    - assets/data/shrimp_respiration_salinity_temperature_weight.json
    - web/assets/wave.svg
    - web/icons/aerasync64.webp
    - web/icons/aerasync64.png
    - web/icons/aerasync180.webp
    - web/icons/aerasync180.png
    - web/icons/aerasync512.webp
    - web/icons/aerasync512.png
    - web/icons/aerasync1024.webp
    - web/icons/aerasync1024.png
    - web/icons/aerasync.webp
    - web/manifest.json