name: AeraSync
description: A new Flutter project.
# Prevent accidental publishing to pub.dev.
publish_to: 'none'
version: 1.0.0+1

environment:
  # Defines the Dart SDK version constraints for the project.
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Core Flutter framework.
  flutter:
    sdk: flutter
  # Support for internationalization and localization.
  flutter_localizations:
    sdk: flutter
  # State management solution.
  provider: ^6.1.2
  # Charting library.
  fl_chart: ^0.70.2
  # Provides access to web APIs (like Blob, Url) in a platform-independent way.
  universal_html: ^2.2.4
  # Plugin for interacting with the system clipboard.
  clipboard: ^0.1.3
  # Provides internationalization and localization utilities (required by flutter_localizations).
  # Note: Version ^0.19.0 is specified. Ensure compatibility or update if needed.
  intl: ^0.19.0
  # Plugin for launching URLs.
  url_launcher: ^6.3.0

dev_dependencies:
  # Flutter testing framework.
  flutter_test:
    sdk: flutter
  # Recommended lint rules for Flutter projects.
  # Note: Version ^5.0.0 requires Dart SDK >= 3.5.0. Adjust if using older SDK.
  flutter_lints: ^5.0.0
  # Mocking library for testing.
  mockito: ^5.4.4

# Flutter-specific configuration.
flutter:
  # Indicates the project uses Material Design.
  uses-material-design: true

  # Enables generation features, including for localization.
  generate: true


  # Declares assets to be included with the application.
  assets:
    # Directory containing data files used by calculators.
    - assets/data/o2_temp_sal_100_sat.json
    - assets/data/shrimp_respiration_salinity_temperature_weight.json
    # Web-specific assets used directly by index.html or manifest.json.
    # Flutter's web build process typically makes the 'web' directory contents
    # available at the root of the deployed application.
    - web/assets/wave.svg
    - web/icons/aerasync64.webp
    - web/icons/aerasync64.png
    - web/icons/aerasync180.webp
    - web/icons/aerasync180.png
    - web/icons/aerasync512.webp
    - web/icons/aerasync512.png
    - web/icons/aerasync1024.webp
    - web/icons/aerasync1024.png
    - web/icons/aerasync.webp # Icon used in index.html loading screen
    - web/manifest.json # Web App Manifest file

