name: CI/CD Pipeline for AeraSync

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: AeraSync

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          cache: true

      - name: Verify Flutter version
        run: flutter --version
        working-directory: AeraSync/AeraSync

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: /home/runner/.pub-cache
          key: flutter-pub-${{ runner.os }}-stable-3.29.2-${{ hashFiles('AeraSync/AeraSync/pubspec.lock') }}
          restore-keys: |
            flutter-pub-${{ runner.os }}-stable-3.29.2-

      - name: Clean project
        run: flutter clean
        working-directory: AeraSync/AeraSync

      - name: Get dependencies
        run: flutter pub get
        working-directory: AeraSync/AeraSync

      - name: Verify required assets
        run: |
          MISSING=false
          for asset in \
            web/icons/aerasync64.webp \
            web/icons/aerasync64.png \
            web/icons/aerasync180.webp \
            web/icons/aerasync180.png \
            web/icons/aerasync512.webp \
            web/icons/aerasync512.png \
            web/icons/aerasync1024.webp \
            web/icons/aerasync1024.png \
            web/icons/aerasync.webp \
            web/assets/wave.svg \
            web/manifest.json \
            web/privacy.html \
            assets/fonts/Montserrat/static/Montserrat.ttf \
            assets/data/shrimp_respiration_salinity_temperature_weight.json \
            assets/data/o2_temp_sal_100_sat.json \
            lib/l10n/app_en.arb; do
            if [ ! -f "$asset" ]; then
              echo "Error: Required asset/file '$asset' is missing"
              MISSING=true
            fi
          done
          if [ "$MISSING" = true ]; then exit 1; fi
        working-directory: AeraSync/AeraSync

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi[all] uvicorn scipy numpy sqlite3
        working-directory: AeraSync/backend

      - name: Start FastAPI backend
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 10
          curl --retry 5 --retry-delay 2 --fail http://localhost:8000/health || exit 1
        working-directory: AeraSync/backend

      - name: Generate localization files
        run: flutter gen-l10n
        working-directory: AeraSync/AeraSync

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs
        working-directory: AeraSync/AeraSync

      - name: Run tests
        run: flutter test
        working-directory: AeraSync/AeraSync

      - name: Lint Python backend
        run: |
          pip install flake8
          flake8 backend/ --max-line-length=79
        working-directory: AeraSync

      - name: Check ARB Key Consistency
        run: |
          echo "Checking consistency of localization keys..."
          python3 scripts/verify_arb.py
        working-directory: AeraSync
        env:
          PYTHONPATH: .

      - name: Build web release
        run: flutter build web --dart-define=flutter.web.renderer=canvaskit --release --base-href=/AeraSync/ --dart-define=API_BASE_URL=http://localhost:8000
        working-directory: AeraSync/AeraSync

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: AeraSync/AeraSync/build/web
          publish_branch: gh-pages
          commit_message: "Deploy build for commit ${{ github.sha }}"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'