name: Deploy Frontend to GitHub Pages and Vercel

on:
  push:
    branches: ["gh-pages"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          cache: true

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: /home/runner/.pub-cache
          key: flutter-pub-${{ runner.os }}-stable-3.29.2-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            flutter-pub-${{ runner.os }}-stable-3.29.2-

      - name: Get dependencies
        run: flutter pub get

      - name: Generate localization files
        run: flutter gen-l10n

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build web for production
        run: flutter build web --dart-define=flutter.web.renderer=canvaskit --release --base-href=/AeraSync/ --dart-define=API_URL=https://aerasync-backend.vercel.app/
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          commit_message: "Deploy frontend for commit ${{ github.sha }}"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
          working-directory: build/web
          scope: ${{ secrets.VERCEL_ORG_ID }}